package com.sequenceiq.cloudbreak.audit.model;

public enum AuditEventName {
    DATAHUB_CLUSTER_CREATION,
    DATAHUB_CLUSTER_DELETION,
    DATAHUB_CLUSTER_STOPPAGE,
    DATAHUB_CLUSTER_RESIZING,
    DATAHUB_CLUSTER_MANUAL_REPAIR,
    DATAHUB_CLUSTER_SYNC,
    DATAHUB_CLUSTER_RETRY,
    DATAHUB_CLUSTER_INSTANCE_DELETION,
    DATAHUB_CLUSTER_MAINTENANCE,
    DATAHUB_CLUSTER_STARTING
}
